// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UkrStanko.Models.App.Context;

namespace UkrStanko.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201230195656_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("UkrStanko.Models.App.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("MachineTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MachineTypeId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MachineTypeId = 3,
                            Name = "16К20"
                        },
                        new
                        {
                            Id = 2,
                            MachineTypeId = 3,
                            Name = "1К62"
                        },
                        new
                        {
                            Id = 3,
                            MachineTypeId = 3,
                            Name = "КА280"
                        },
                        new
                        {
                            Id = 4,
                            MachineTypeId = 3,
                            Name = "ТС70"
                        },
                        new
                        {
                            Id = 5,
                            MachineTypeId = 3,
                            Name = "ТС75"
                        },
                        new
                        {
                            Id = 6,
                            MachineTypeId = 3,
                            Name = "ТС25"
                        },
                        new
                        {
                            Id = 7,
                            MachineTypeId = 3,
                            Name = "ТС20"
                        },
                        new
                        {
                            Id = 8,
                            MachineTypeId = 3,
                            Name = "ДИП200"
                        },
                        new
                        {
                            Id = 9,
                            MachineTypeId = 3,
                            Name = "1К62Д"
                        },
                        new
                        {
                            Id = 10,
                            MachineTypeId = 3,
                            Name = "ИТ1М"
                        },
                        new
                        {
                            Id = 11,
                            MachineTypeId = 3,
                            Name = "ЛТ10"
                        },
                        new
                        {
                            Id = 12,
                            MachineTypeId = 3,
                            Name = "16К25"
                        },
                        new
                        {
                            Id = 13,
                            MachineTypeId = 3,
                            Name = "16Д20"
                        },
                        new
                        {
                            Id = 14,
                            MachineTypeId = 3,
                            Name = "16Д25"
                        },
                        new
                        {
                            Id = 15,
                            MachineTypeId = 3,
                            Name = "ФТ11"
                        },
                        new
                        {
                            Id = 16,
                            MachineTypeId = 3,
                            Name = "16Е20"
                        },
                        new
                        {
                            Id = 17,
                            MachineTypeId = 3,
                            Name = "МК6056"
                        },
                        new
                        {
                            Id = 18,
                            MachineTypeId = 3,
                            Name = "1К625"
                        },
                        new
                        {
                            Id = 19,
                            MachineTypeId = 3,
                            Name = "ЛТ11"
                        },
                        new
                        {
                            Id = 20,
                            MachineTypeId = 3,
                            Name = "1В62Г"
                        },
                        new
                        {
                            Id = 21,
                            MachineTypeId = 3,
                            Name = "1В62"
                        },
                        new
                        {
                            Id = 22,
                            MachineTypeId = 3,
                            Name = "16К25Г"
                        },
                        new
                        {
                            Id = 23,
                            MachineTypeId = 3,
                            Name = "С11"
                        },
                        new
                        {
                            Id = 24,
                            MachineTypeId = 3,
                            Name = "SNA400"
                        },
                        new
                        {
                            Id = 25,
                            MachineTypeId = 3,
                            Name = "SNA500"
                        },
                        new
                        {
                            Id = 26,
                            MachineTypeId = 3,
                            Name = "SNB500"
                        },
                        new
                        {
                            Id = 27,
                            MachineTypeId = 4,
                            Name = "1И611П"
                        },
                        new
                        {
                            Id = 28,
                            MachineTypeId = 4,
                            Name = "ИЖ250"
                        },
                        new
                        {
                            Id = 29,
                            MachineTypeId = 4,
                            Name = "ИЖ250ИТП"
                        },
                        new
                        {
                            Id = 30,
                            MachineTypeId = 4,
                            Name = "ИЖ250ИТВ"
                        },
                        new
                        {
                            Id = 31,
                            MachineTypeId = 4,
                            Name = "ИЖ250ИТВМ"
                        },
                        new
                        {
                            Id = 32,
                            MachineTypeId = 4,
                            Name = "16Б05"
                        },
                        new
                        {
                            Id = 33,
                            MachineTypeId = 4,
                            Name = "95ТС-1"
                        },
                        new
                        {
                            Id = 34,
                            MachineTypeId = 4,
                            Name = "ИЖ"
                        },
                        new
                        {
                            Id = 35,
                            MachineTypeId = 4,
                            Name = "ИС1-1"
                        },
                        new
                        {
                            Id = 36,
                            MachineTypeId = 4,
                            Name = "16И05"
                        },
                        new
                        {
                            Id = 37,
                            MachineTypeId = 5,
                            Name = "16Б16КП"
                        },
                        new
                        {
                            Id = 38,
                            MachineTypeId = 5,
                            Name = "16Б16КА"
                        },
                        new
                        {
                            Id = 39,
                            MachineTypeId = 5,
                            Name = "16Б16П"
                        },
                        new
                        {
                            Id = 40,
                            MachineTypeId = 5,
                            Name = "ТВ320"
                        },
                        new
                        {
                            Id = 41,
                            MachineTypeId = 5,
                            Name = "1А616"
                        },
                        new
                        {
                            Id = 42,
                            MachineTypeId = 5,
                            Name = "1М61"
                        },
                        new
                        {
                            Id = 43,
                            MachineTypeId = 5,
                            Name = "УТ16"
                        },
                        new
                        {
                            Id = 44,
                            MachineTypeId = 5,
                            Name = "1Е61"
                        },
                        new
                        {
                            Id = 45,
                            MachineTypeId = 6,
                            Name = "16А20Ф3"
                        },
                        new
                        {
                            Id = 46,
                            MachineTypeId = 6,
                            Name = "16А20Ф3С39"
                        },
                        new
                        {
                            Id = 47,
                            MachineTypeId = 6,
                            Name = "16А20ТС1"
                        },
                        new
                        {
                            Id = 48,
                            MachineTypeId = 6,
                            Name = "16А20Ф3С42"
                        },
                        new
                        {
                            Id = 49,
                            MachineTypeId = 6,
                            Name = "16К20Т1"
                        },
                        new
                        {
                            Id = 50,
                            MachineTypeId = 6,
                            Name = "16К20Ф3"
                        },
                        new
                        {
                            Id = 51,
                            MachineTypeId = 7,
                            Name = "ДИП300"
                        },
                        new
                        {
                            Id = 52,
                            MachineTypeId = 7,
                            Name = "1М63"
                        },
                        new
                        {
                            Id = 53,
                            MachineTypeId = 7,
                            Name = "163"
                        },
                        new
                        {
                            Id = 54,
                            MachineTypeId = 7,
                            Name = "1М63Н"
                        },
                        new
                        {
                            Id = 55,
                            MachineTypeId = 7,
                            Name = "1М63Ф101"
                        },
                        new
                        {
                            Id = 56,
                            MachineTypeId = 7,
                            Name = "1М63БФ101"
                        },
                        new
                        {
                            Id = 57,
                            MachineTypeId = 8,
                            Name = "16К40"
                        },
                        new
                        {
                            Id = 58,
                            MachineTypeId = 8,
                            Name = "16К40Ф101"
                        },
                        new
                        {
                            Id = 59,
                            MachineTypeId = 8,
                            Name = "ДИП400"
                        },
                        new
                        {
                            Id = 60,
                            MachineTypeId = 8,
                            Name = "1А64"
                        },
                        new
                        {
                            Id = 61,
                            MachineTypeId = 9,
                            Name = "ДИП500"
                        },
                        new
                        {
                            Id = 62,
                            MachineTypeId = 9,
                            Name = "1М65"
                        },
                        new
                        {
                            Id = 63,
                            MachineTypeId = 9,
                            Name = "165"
                        },
                        new
                        {
                            Id = 64,
                            MachineTypeId = 9,
                            Name = "1Н65"
                        },
                        new
                        {
                            Id = 65,
                            MachineTypeId = 11,
                            Name = "675"
                        },
                        new
                        {
                            Id = 66,
                            MachineTypeId = 11,
                            Name = "6А75"
                        },
                        new
                        {
                            Id = 67,
                            MachineTypeId = 11,
                            Name = "675П"
                        },
                        new
                        {
                            Id = 68,
                            MachineTypeId = 11,
                            Name = "6720В"
                        },
                        new
                        {
                            Id = 69,
                            MachineTypeId = 11,
                            Name = "6720ВФ1"
                        },
                        new
                        {
                            Id = 70,
                            MachineTypeId = 11,
                            Name = "6Б75"
                        },
                        new
                        {
                            Id = 71,
                            MachineTypeId = 11,
                            Name = "67К20"
                        },
                        new
                        {
                            Id = 72,
                            MachineTypeId = 11,
                            Name = "67М20"
                        },
                        new
                        {
                            Id = 73,
                            MachineTypeId = 11,
                            Name = "СФ55"
                        },
                        new
                        {
                            Id = 74,
                            MachineTypeId = 12,
                            Name = "676"
                        },
                        new
                        {
                            Id = 75,
                            MachineTypeId = 12,
                            Name = "676П"
                        },
                        new
                        {
                            Id = 76,
                            MachineTypeId = 12,
                            Name = "ВМ130"
                        },
                        new
                        {
                            Id = 77,
                            MachineTypeId = 12,
                            Name = "6Б76"
                        },
                        new
                        {
                            Id = 78,
                            MachineTypeId = 12,
                            Name = "67К25"
                        },
                        new
                        {
                            Id = 79,
                            MachineTypeId = 12,
                            Name = "6725П"
                        },
                        new
                        {
                            Id = 80,
                            MachineTypeId = 12,
                            Name = "67К25В"
                        },
                        new
                        {
                            Id = 81,
                            MachineTypeId = 12,
                            Name = "ВМ130М"
                        },
                        new
                        {
                            Id = 82,
                            MachineTypeId = 12,
                            Name = "67К25ПФ1"
                        },
                        new
                        {
                            Id = 83,
                            MachineTypeId = 12,
                            Name = "СФ676"
                        },
                        new
                        {
                            Id = 84,
                            MachineTypeId = 12,
                            Name = "FU315"
                        },
                        new
                        {
                            Id = 85,
                            MachineTypeId = 12,
                            Name = "6Т80Ш"
                        },
                        new
                        {
                            Id = 86,
                            MachineTypeId = 12,
                            Name = "6Р80Ш"
                        },
                        new
                        {
                            Id = 87,
                            MachineTypeId = 13,
                            Name = "6Р12"
                        },
                        new
                        {
                            Id = 88,
                            MachineTypeId = 13,
                            Name = "6Т12"
                        },
                        new
                        {
                            Id = 89,
                            MachineTypeId = 13,
                            Name = "FSS315"
                        },
                        new
                        {
                            Id = 90,
                            MachineTypeId = 13,
                            Name = "СФ35"
                        },
                        new
                        {
                            Id = 91,
                            MachineTypeId = 13,
                            Name = "СФ40"
                        },
                        new
                        {
                            Id = 92,
                            MachineTypeId = 13,
                            Name = "6Т12Ф20"
                        },
                        new
                        {
                            Id = 93,
                            MachineTypeId = 13,
                            Name = "6М12"
                        },
                        new
                        {
                            Id = 94,
                            MachineTypeId = 14,
                            Name = "6Р82"
                        },
                        new
                        {
                            Id = 95,
                            MachineTypeId = 14,
                            Name = "6Т82"
                        },
                        new
                        {
                            Id = 96,
                            MachineTypeId = 14,
                            Name = "6Р82Г"
                        },
                        new
                        {
                            Id = 97,
                            MachineTypeId = 14,
                            Name = "6Т82Г"
                        },
                        new
                        {
                            Id = 98,
                            MachineTypeId = 15,
                            Name = "6Р82Ш"
                        },
                        new
                        {
                            Id = 99,
                            MachineTypeId = 15,
                            Name = "6Т82Ш"
                        },
                        new
                        {
                            Id = 100,
                            MachineTypeId = 15,
                            Name = "6Д82Ш"
                        },
                        new
                        {
                            Id = 101,
                            MachineTypeId = 15,
                            Name = "6М82Ш"
                        },
                        new
                        {
                            Id = 102,
                            MachineTypeId = 16,
                            Name = "6Р13"
                        },
                        new
                        {
                            Id = 103,
                            MachineTypeId = 16,
                            Name = "6Т13"
                        },
                        new
                        {
                            Id = 104,
                            MachineTypeId = 16,
                            Name = "FSS400"
                        },
                        new
                        {
                            Id = 105,
                            MachineTypeId = 16,
                            Name = "6М13"
                        },
                        new
                        {
                            Id = 106,
                            MachineTypeId = 16,
                            Name = "ВМ127"
                        },
                        new
                        {
                            Id = 107,
                            MachineTypeId = 17,
                            Name = "6Р83"
                        },
                        new
                        {
                            Id = 108,
                            MachineTypeId = 17,
                            Name = "6Р83Г"
                        },
                        new
                        {
                            Id = 109,
                            MachineTypeId = 17,
                            Name = "6Т83"
                        },
                        new
                        {
                            Id = 110,
                            MachineTypeId = 17,
                            Name = "6Т83Г"
                        },
                        new
                        {
                            Id = 111,
                            MachineTypeId = 18,
                            Name = "6Р83Ш"
                        },
                        new
                        {
                            Id = 112,
                            MachineTypeId = 18,
                            Name = "6Т83Ш"
                        },
                        new
                        {
                            Id = 113,
                            MachineTypeId = 18,
                            Name = "FU400"
                        },
                        new
                        {
                            Id = 114,
                            MachineTypeId = 20,
                            Name = "2Н135"
                        },
                        new
                        {
                            Id = 115,
                            MachineTypeId = 20,
                            Name = "2С132"
                        },
                        new
                        {
                            Id = 116,
                            MachineTypeId = 21,
                            Name = "2Н125"
                        },
                        new
                        {
                            Id = 117,
                            MachineTypeId = 21,
                            Name = "2Г125"
                        },
                        new
                        {
                            Id = 118,
                            MachineTypeId = 21,
                            Name = "2С125"
                        },
                        new
                        {
                            Id = 119,
                            MachineTypeId = 22,
                            Name = "2Н118"
                        },
                        new
                        {
                            Id = 120,
                            MachineTypeId = 22,
                            Name = "МН18"
                        },
                        new
                        {
                            Id = 121,
                            MachineTypeId = 23,
                            Name = "2М112"
                        },
                        new
                        {
                            Id = 122,
                            MachineTypeId = 23,
                            Name = "НС12"
                        },
                        new
                        {
                            Id = 123,
                            MachineTypeId = 23,
                            Name = "СНС12"
                        },
                        new
                        {
                            Id = 124,
                            MachineTypeId = 25,
                            Name = "2620"
                        },
                        new
                        {
                            Id = 125,
                            MachineTypeId = 25,
                            Name = "2А620"
                        },
                        new
                        {
                            Id = 126,
                            MachineTypeId = 25,
                            Name = "2А620Ф1"
                        },
                        new
                        {
                            Id = 127,
                            MachineTypeId = 25,
                            Name = "2А620Ф11"
                        },
                        new
                        {
                            Id = 128,
                            MachineTypeId = 25,
                            Name = "2А620Ф2"
                        },
                        new
                        {
                            Id = 129,
                            MachineTypeId = 25,
                            Name = "2А620Ф20"
                        },
                        new
                        {
                            Id = 130,
                            MachineTypeId = 25,
                            Name = "2620ВФ1"
                        },
                        new
                        {
                            Id = 131,
                            MachineTypeId = 25,
                            Name = "2620Ф11"
                        },
                        new
                        {
                            Id = 132,
                            MachineTypeId = 25,
                            Name = "2620Е"
                        },
                        new
                        {
                            Id = 133,
                            MachineTypeId = 25,
                            Name = "2620В"
                        },
                        new
                        {
                            Id = 134,
                            MachineTypeId = 25,
                            Name = "2620ГФ1"
                        },
                        new
                        {
                            Id = 135,
                            MachineTypeId = 26,
                            Name = "2622"
                        },
                        new
                        {
                            Id = 136,
                            MachineTypeId = 26,
                            Name = "2622ГФ1"
                        },
                        new
                        {
                            Id = 137,
                            MachineTypeId = 26,
                            Name = "2622Г"
                        },
                        new
                        {
                            Id = 138,
                            MachineTypeId = 26,
                            Name = "2622В"
                        },
                        new
                        {
                            Id = 139,
                            MachineTypeId = 26,
                            Name = "2622ВФ1"
                        },
                        new
                        {
                            Id = 140,
                            MachineTypeId = 26,
                            Name = "2А622"
                        },
                        new
                        {
                            Id = 141,
                            MachineTypeId = 26,
                            Name = "2А622Ф2"
                        },
                        new
                        {
                            Id = 142,
                            MachineTypeId = 26,
                            Name = "2А622Ф1"
                        },
                        new
                        {
                            Id = 143,
                            MachineTypeId = 26,
                            Name = "2А622Ф11"
                        },
                        new
                        {
                            Id = 144,
                            MachineTypeId = 26,
                            Name = "2А622Ф20"
                        },
                        new
                        {
                            Id = 145,
                            MachineTypeId = 26,
                            Name = "2А622МФ2"
                        },
                        new
                        {
                            Id = 146,
                            MachineTypeId = 27,
                            Name = "2Л614"
                        },
                        new
                        {
                            Id = 147,
                            MachineTypeId = 27,
                            Name = "2М614"
                        },
                        new
                        {
                            Id = 148,
                            MachineTypeId = 27,
                            Name = "2М614ГФ1"
                        },
                        new
                        {
                            Id = 149,
                            MachineTypeId = 27,
                            Name = "2Н614"
                        },
                        new
                        {
                            Id = 150,
                            MachineTypeId = 27,
                            Name = "2А614"
                        },
                        new
                        {
                            Id = 151,
                            MachineTypeId = 27,
                            Name = "2Л614Ф1"
                        },
                        new
                        {
                            Id = 152,
                            MachineTypeId = 29,
                            Name = "3Г71"
                        },
                        new
                        {
                            Id = 153,
                            MachineTypeId = 29,
                            Name = "3Г71М"
                        },
                        new
                        {
                            Id = 154,
                            MachineTypeId = 29,
                            Name = "3Е711"
                        },
                        new
                        {
                            Id = 155,
                            MachineTypeId = 29,
                            Name = "3Е711ВФ1"
                        },
                        new
                        {
                            Id = 156,
                            MachineTypeId = 29,
                            Name = "3Е711ВФ11"
                        },
                        new
                        {
                            Id = 157,
                            MachineTypeId = 29,
                            Name = "3Е711В"
                        },
                        new
                        {
                            Id = 158,
                            MachineTypeId = 29,
                            Name = "3Д711"
                        },
                        new
                        {
                            Id = 159,
                            MachineTypeId = 29,
                            Name = "3Д711АФ10"
                        },
                        new
                        {
                            Id = 160,
                            MachineTypeId = 29,
                            Name = "3Д711ВФ11"
                        },
                        new
                        {
                            Id = 161,
                            MachineTypeId = 29,
                            Name = "3Д711АФ1"
                        },
                        new
                        {
                            Id = 162,
                            MachineTypeId = 29,
                            Name = "ОШ55"
                        },
                        new
                        {
                            Id = 163,
                            MachineTypeId = 30,
                            Name = "3Б722"
                        },
                        new
                        {
                            Id = 164,
                            MachineTypeId = 30,
                            Name = "3Л722"
                        },
                        new
                        {
                            Id = 165,
                            MachineTypeId = 30,
                            Name = "3Л722В"
                        },
                        new
                        {
                            Id = 166,
                            MachineTypeId = 30,
                            Name = "3Л722А"
                        },
                        new
                        {
                            Id = 167,
                            MachineTypeId = 30,
                            Name = "3Д722"
                        },
                        new
                        {
                            Id = 168,
                            MachineTypeId = 31,
                            Name = "3Б151"
                        },
                        new
                        {
                            Id = 169,
                            MachineTypeId = 31,
                            Name = "3М151"
                        },
                        new
                        {
                            Id = 170,
                            MachineTypeId = 31,
                            Name = "3А151"
                        },
                        new
                        {
                            Id = 171,
                            MachineTypeId = 31,
                            Name = "3М152"
                        },
                        new
                        {
                            Id = 172,
                            MachineTypeId = 31,
                            Name = "3М152В"
                        },
                        new
                        {
                            Id = 173,
                            MachineTypeId = 31,
                            Name = "3М152ВМ"
                        },
                        new
                        {
                            Id = 174,
                            MachineTypeId = 31,
                            Name = "3М152ВФ20"
                        },
                        new
                        {
                            Id = 175,
                            MachineTypeId = 31,
                            Name = "3А130"
                        },
                        new
                        {
                            Id = 176,
                            MachineTypeId = 31,
                            Name = "3У130"
                        },
                        new
                        {
                            Id = 177,
                            MachineTypeId = 31,
                            Name = "3У131"
                        },
                        new
                        {
                            Id = 178,
                            MachineTypeId = 31,
                            Name = "3У131В"
                        },
                        new
                        {
                            Id = 179,
                            MachineTypeId = 31,
                            Name = "3М131"
                        },
                        new
                        {
                            Id = 180,
                            MachineTypeId = 31,
                            Name = "3У131М"
                        },
                        new
                        {
                            Id = 181,
                            MachineTypeId = 31,
                            Name = "3У131ВМ"
                        },
                        new
                        {
                            Id = 182,
                            MachineTypeId = 31,
                            Name = "3У132ВМ"
                        },
                        new
                        {
                            Id = 183,
                            MachineTypeId = 31,
                            Name = "3М161"
                        },
                        new
                        {
                            Id = 184,
                            MachineTypeId = 31,
                            Name = "3М161ВФ20"
                        },
                        new
                        {
                            Id = 185,
                            MachineTypeId = 31,
                            Name = "3У132"
                        },
                        new
                        {
                            Id = 186,
                            MachineTypeId = 31,
                            Name = "3У132В"
                        },
                        new
                        {
                            Id = 187,
                            MachineTypeId = 31,
                            Name = "3Б161"
                        },
                        new
                        {
                            Id = 188,
                            MachineTypeId = 31,
                            Name = "3У132М"
                        },
                        new
                        {
                            Id = 189,
                            MachineTypeId = 31,
                            Name = "3М132"
                        },
                        new
                        {
                            Id = 190,
                            MachineTypeId = 31,
                            Name = "3М132МВФ2"
                        },
                        new
                        {
                            Id = 191,
                            MachineTypeId = 31,
                            Name = "3В161"
                        },
                        new
                        {
                            Id = 192,
                            MachineTypeId = 31,
                            Name = "3М162"
                        },
                        new
                        {
                            Id = 193,
                            MachineTypeId = 31,
                            Name = "3М162В"
                        },
                        new
                        {
                            Id = 194,
                            MachineTypeId = 31,
                            Name = "3М162МВФ2"
                        },
                        new
                        {
                            Id = 195,
                            MachineTypeId = 31,
                            Name = "3У133"
                        },
                        new
                        {
                            Id = 196,
                            MachineTypeId = 32,
                            Name = "3У142"
                        },
                        new
                        {
                            Id = 197,
                            MachineTypeId = 32,
                            Name = "3У142В"
                        },
                        new
                        {
                            Id = 198,
                            MachineTypeId = 32,
                            Name = "3У142МВ"
                        },
                        new
                        {
                            Id = 199,
                            MachineTypeId = 32,
                            Name = "3У142МВФ2"
                        },
                        new
                        {
                            Id = 200,
                            MachineTypeId = 32,
                            Name = "3У143"
                        },
                        new
                        {
                            Id = 201,
                            MachineTypeId = 32,
                            Name = "3У144"
                        },
                        new
                        {
                            Id = 202,
                            MachineTypeId = 32,
                            Name = "3М143МВ"
                        },
                        new
                        {
                            Id = 203,
                            MachineTypeId = 32,
                            Name = "3А164"
                        },
                        new
                        {
                            Id = 204,
                            MachineTypeId = 32,
                            Name = "3А164Б"
                        },
                        new
                        {
                            Id = 205,
                            MachineTypeId = 32,
                            Name = "3У143МВФ2"
                        },
                        new
                        {
                            Id = 206,
                            MachineTypeId = 32,
                            Name = "3У143МВ"
                        },
                        new
                        {
                            Id = 207,
                            MachineTypeId = 32,
                            Name = "3В164"
                        },
                        new
                        {
                            Id = 208,
                            MachineTypeId = 32,
                            Name = "3М173"
                        },
                        new
                        {
                            Id = 209,
                            MachineTypeId = 32,
                            Name = "3М173МВФ2"
                        },
                        new
                        {
                            Id = 210,
                            MachineTypeId = 33,
                            Name = "3У144МВФ2"
                        },
                        new
                        {
                            Id = 211,
                            MachineTypeId = 33,
                            Name = "3М174"
                        },
                        new
                        {
                            Id = 212,
                            MachineTypeId = 33,
                            Name = "3М174В"
                        },
                        new
                        {
                            Id = 213,
                            MachineTypeId = 35,
                            Name = "7А420"
                        },
                        new
                        {
                            Id = 214,
                            MachineTypeId = 35,
                            Name = "7402"
                        },
                        new
                        {
                            Id = 215,
                            MachineTypeId = 36,
                            Name = "7М430"
                        },
                        new
                        {
                            Id = 216,
                            MachineTypeId = 36,
                            Name = "7Д430"
                        },
                        new
                        {
                            Id = 217,
                            MachineTypeId = 36,
                            Name = "7403"
                        },
                        new
                        {
                            Id = 218,
                            MachineTypeId = 36,
                            Name = "ГД320"
                        },
                        new
                        {
                            Id = 219,
                            MachineTypeId = 37,
                            Name = "7405"
                        },
                        new
                        {
                            Id = 220,
                            MachineTypeId = 37,
                            Name = "7Д450"
                        },
                        new
                        {
                            Id = 221,
                            MachineTypeId = 37,
                            Name = "7М450"
                        },
                        new
                        {
                            Id = 222,
                            MachineTypeId = 37,
                            Name = "ГД500"
                        },
                        new
                        {
                            Id = 223,
                            MachineTypeId = 39,
                            Name = "5К310"
                        },
                        new
                        {
                            Id = 224,
                            MachineTypeId = 39,
                            Name = "53А20"
                        },
                        new
                        {
                            Id = 225,
                            MachineTypeId = 39,
                            Name = "5306"
                        },
                        new
                        {
                            Id = 226,
                            MachineTypeId = 40,
                            Name = "53А30"
                        },
                        new
                        {
                            Id = 227,
                            MachineTypeId = 40,
                            Name = "5Д312"
                        },
                        new
                        {
                            Id = 228,
                            MachineTypeId = 40,
                            Name = "5В312"
                        },
                        new
                        {
                            Id = 229,
                            MachineTypeId = 40,
                            Name = "5Д312ЕЗ60"
                        },
                        new
                        {
                            Id = 230,
                            MachineTypeId = 41,
                            Name = "53А50"
                        },
                        new
                        {
                            Id = 231,
                            MachineTypeId = 41,
                            Name = "5К324"
                        },
                        new
                        {
                            Id = 232,
                            MachineTypeId = 41,
                            Name = "5К324А"
                        },
                        new
                        {
                            Id = 233,
                            MachineTypeId = 41,
                            Name = "5Е32"
                        },
                        new
                        {
                            Id = 234,
                            MachineTypeId = 42,
                            Name = "5К32"
                        },
                        new
                        {
                            Id = 235,
                            MachineTypeId = 42,
                            Name = "5К32А"
                        },
                        new
                        {
                            Id = 236,
                            MachineTypeId = 42,
                            Name = "53А80"
                        },
                        new
                        {
                            Id = 237,
                            MachineTypeId = 42,
                            Name = "53А80Н"
                        },
                        new
                        {
                            Id = 238,
                            MachineTypeId = 42,
                            Name = "53А80К"
                        },
                        new
                        {
                            Id = 239,
                            MachineTypeId = 42,
                            Name = "53А80Д"
                        },
                        new
                        {
                            Id = 240,
                            MachineTypeId = 44,
                            Name = "КД2130"
                        },
                        new
                        {
                            Id = 241,
                            MachineTypeId = 44,
                            Name = "КЕ2130"
                        },
                        new
                        {
                            Id = 242,
                            MachineTypeId = 44,
                            Name = "К2130"
                        },
                        new
                        {
                            Id = 243,
                            MachineTypeId = 44,
                            Name = "КД2330"
                        },
                        new
                        {
                            Id = 244,
                            MachineTypeId = 44,
                            Name = "К1430"
                        },
                        new
                        {
                            Id = 245,
                            MachineTypeId = 44,
                            Name = "КЕ2330"
                        },
                        new
                        {
                            Id = 246,
                            MachineTypeId = 44,
                            Name = "КЕ1430"
                        },
                        new
                        {
                            Id = 247,
                            MachineTypeId = 45,
                            Name = "К2128"
                        },
                        new
                        {
                            Id = 248,
                            MachineTypeId = 45,
                            Name = "КИ1428"
                        },
                        new
                        {
                            Id = 249,
                            MachineTypeId = 45,
                            Name = "КД2128Е"
                        },
                        new
                        {
                            Id = 250,
                            MachineTypeId = 45,
                            Name = "КД2128К"
                        },
                        new
                        {
                            Id = 251,
                            MachineTypeId = 45,
                            Name = "КД2328К"
                        },
                        new
                        {
                            Id = 252,
                            MachineTypeId = 45,
                            Name = "КД2328"
                        },
                        new
                        {
                            Id = 253,
                            MachineTypeId = 45,
                            Name = "КД1428"
                        },
                        new
                        {
                            Id = 254,
                            MachineTypeId = 45,
                            Name = "КИ2128"
                        },
                        new
                        {
                            Id = 255,
                            MachineTypeId = 45,
                            Name = "КД2128"
                        },
                        new
                        {
                            Id = 256,
                            MachineTypeId = 46,
                            Name = "КД2126"
                        },
                        new
                        {
                            Id = 257,
                            MachineTypeId = 46,
                            Name = "К2126"
                        },
                        new
                        {
                            Id = 258,
                            MachineTypeId = 46,
                            Name = "КД2326"
                        },
                        new
                        {
                            Id = 259,
                            MachineTypeId = 46,
                            Name = "КД1426"
                        },
                        new
                        {
                            Id = 260,
                            MachineTypeId = 46,
                            Name = "КИ1426"
                        },
                        new
                        {
                            Id = 261,
                            MachineTypeId = 46,
                            Name = "КД2326А"
                        },
                        new
                        {
                            Id = 262,
                            MachineTypeId = 46,
                            Name = "КД2126К"
                        },
                        new
                        {
                            Id = 263,
                            MachineTypeId = 46,
                            Name = "КД1426Б"
                        },
                        new
                        {
                            Id = 264,
                            MachineTypeId = 46,
                            Name = "КИ2126"
                        },
                        new
                        {
                            Id = 265,
                            MachineTypeId = 47,
                            Name = "КД2324"
                        },
                        new
                        {
                            Id = 266,
                            MachineTypeId = 47,
                            Name = "КД2324Е"
                        },
                        new
                        {
                            Id = 267,
                            MachineTypeId = 47,
                            Name = "КД1424"
                        },
                        new
                        {
                            Id = 268,
                            MachineTypeId = 47,
                            Name = "КД2124"
                        },
                        new
                        {
                            Id = 269,
                            MachineTypeId = 47,
                            Name = "КД2124Е"
                        },
                        new
                        {
                            Id = 270,
                            MachineTypeId = 47,
                            Name = "КД2324В"
                        },
                        new
                        {
                            Id = 271,
                            MachineTypeId = 47,
                            Name = "КД2124К"
                        },
                        new
                        {
                            Id = 272,
                            MachineTypeId = 47,
                            Name = "КД2324К"
                        },
                        new
                        {
                            Id = 273,
                            MachineTypeId = 47,
                            Name = "КД1424Б"
                        },
                        new
                        {
                            Id = 274,
                            MachineTypeId = 47,
                            Name = "КД1424К"
                        },
                        new
                        {
                            Id = 275,
                            MachineTypeId = 47,
                            Name = "КД2124Г"
                        },
                        new
                        {
                            Id = 276,
                            MachineTypeId = 47,
                            Name = "К2324"
                        },
                        new
                        {
                            Id = 277,
                            MachineTypeId = 48,
                            Name = "КД2322"
                        },
                        new
                        {
                            Id = 278,
                            MachineTypeId = 48,
                            Name = "КД2122"
                        },
                        new
                        {
                            Id = 279,
                            MachineTypeId = 48,
                            Name = "КД2322Г"
                        },
                        new
                        {
                            Id = 280,
                            MachineTypeId = 48,
                            Name = "К2122"
                        },
                        new
                        {
                            Id = 281,
                            MachineTypeId = 48,
                            Name = "КД1422"
                        },
                        new
                        {
                            Id = 282,
                            MachineTypeId = 49,
                            Name = "Д2430"
                        },
                        new
                        {
                            Id = 283,
                            MachineTypeId = 49,
                            Name = "ДЕ2430"
                        },
                        new
                        {
                            Id = 284,
                            MachineTypeId = 49,
                            Name = "ДГ2430"
                        },
                        new
                        {
                            Id = 285,
                            MachineTypeId = 49,
                            Name = "ДБ2430"
                        },
                        new
                        {
                            Id = 286,
                            MachineTypeId = 49,
                            Name = "ДБ2430Б"
                        },
                        new
                        {
                            Id = 287,
                            MachineTypeId = 49,
                            Name = "ДГ2430А"
                        },
                        new
                        {
                            Id = 288,
                            MachineTypeId = 50,
                            Name = "П476"
                        },
                        new
                        {
                            Id = 289,
                            MachineTypeId = 50,
                            Name = "ПД476"
                        },
                        new
                        {
                            Id = 290,
                            MachineTypeId = 50,
                            Name = "Д2432"
                        },
                        new
                        {
                            Id = 291,
                            MachineTypeId = 50,
                            Name = "ДГ2432"
                        },
                        new
                        {
                            Id = 292,
                            MachineTypeId = 50,
                            Name = "ДБ2432"
                        },
                        new
                        {
                            Id = 293,
                            MachineTypeId = 50,
                            Name = "ДГ2432А"
                        },
                        new
                        {
                            Id = 294,
                            MachineTypeId = 50,
                            Name = "ДБ2432А"
                        },
                        new
                        {
                            Id = 295,
                            MachineTypeId = 50,
                            Name = "ДБ2432Б"
                        },
                        new
                        {
                            Id = 296,
                            MachineTypeId = 50,
                            Name = "ДЕ2432"
                        },
                        new
                        {
                            Id = 297,
                            MachineTypeId = 51,
                            Name = "ДЕ2428"
                        },
                        new
                        {
                            Id = 298,
                            MachineTypeId = 51,
                            Name = "ДГ2428"
                        },
                        new
                        {
                            Id = 299,
                            MachineTypeId = 51,
                            Name = "ДГ2428Б"
                        },
                        new
                        {
                            Id = 300,
                            MachineTypeId = 51,
                            Name = "ДВ2428"
                        },
                        new
                        {
                            Id = 301,
                            MachineTypeId = 52,
                            Name = "П6330"
                        },
                        new
                        {
                            Id = 302,
                            MachineTypeId = 52,
                            Name = "PYE100"
                        },
                        new
                        {
                            Id = 303,
                            MachineTypeId = 53,
                            Name = "П6328"
                        },
                        new
                        {
                            Id = 304,
                            MachineTypeId = 53,
                            Name = "PYE63"
                        },
                        new
                        {
                            Id = 305,
                            MachineTypeId = 55,
                            Name = "И2220"
                        },
                        new
                        {
                            Id = 306,
                            MachineTypeId = 55,
                            Name = "ИБ2220"
                        },
                        new
                        {
                            Id = 307,
                            MachineTypeId = 55,
                            Name = "И2220А"
                        },
                        new
                        {
                            Id = 308,
                            MachineTypeId = 55,
                            Name = "И2220Б"
                        },
                        new
                        {
                            Id = 309,
                            MachineTypeId = 55,
                            Name = "ИБ2220Г"
                        },
                        new
                        {
                            Id = 310,
                            MachineTypeId = 55,
                            Name = "ИБ2220Б"
                        },
                        new
                        {
                            Id = 311,
                            MachineTypeId = 55,
                            Name = "ИБ2220В"
                        },
                        new
                        {
                            Id = 312,
                            MachineTypeId = 56,
                            Name = "И2222"
                        },
                        new
                        {
                            Id = 313,
                            MachineTypeId = 56,
                            Name = "ИБ2222"
                        },
                        new
                        {
                            Id = 314,
                            MachineTypeId = 56,
                            Name = "ИБ2222В"
                        },
                        new
                        {
                            Id = 315,
                            MachineTypeId = 56,
                            Name = "И2222Б"
                        },
                        new
                        {
                            Id = 316,
                            MachineTypeId = 56,
                            Name = "ИВ2222"
                        },
                        new
                        {
                            Id = 317,
                            MachineTypeId = 58,
                            Name = "И1330"
                        },
                        new
                        {
                            Id = 318,
                            MachineTypeId = 58,
                            Name = "ИВ1330А"
                        },
                        new
                        {
                            Id = 319,
                            MachineTypeId = 58,
                            Name = "И1330А"
                        },
                        new
                        {
                            Id = 320,
                            MachineTypeId = 58,
                            Name = "ИА1330"
                        },
                        new
                        {
                            Id = 321,
                            MachineTypeId = 59,
                            Name = "И1430"
                        },
                        new
                        {
                            Id = 322,
                            MachineTypeId = 59,
                            Name = "ИА1430А"
                        },
                        new
                        {
                            Id = 323,
                            MachineTypeId = 59,
                            Name = "ИБ1430"
                        },
                        new
                        {
                            Id = 324,
                            MachineTypeId = 59,
                            Name = "ИБ1430Б"
                        },
                        new
                        {
                            Id = 325,
                            MachineTypeId = 59,
                            Name = "ИА1430"
                        });
                });

            modelBuilder.Entity("UkrStanko.Models.App.MachineType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ParentMachineTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.HasIndex("ParentMachineTypeId");

                    b.ToTable("MachineTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Без группы"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Токарные"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Токарные_1",
                            ParentMachineTypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Токарные_2",
                            ParentMachineTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Токарные_3",
                            ParentMachineTypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Токарные_4",
                            ParentMachineTypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Токарные_5",
                            ParentMachineTypeId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Токарные_6",
                            ParentMachineTypeId = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "Токарные_7",
                            ParentMachineTypeId = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "Фрезерные"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Фрезерные_1",
                            ParentMachineTypeId = 10
                        },
                        new
                        {
                            Id = 12,
                            Name = "Фрезерные_2",
                            ParentMachineTypeId = 10
                        },
                        new
                        {
                            Id = 13,
                            Name = "Фрезерные_3",
                            ParentMachineTypeId = 10
                        },
                        new
                        {
                            Id = 14,
                            Name = "Фрезерные_4",
                            ParentMachineTypeId = 10
                        },
                        new
                        {
                            Id = 15,
                            Name = "Фрезерные_5",
                            ParentMachineTypeId = 10
                        },
                        new
                        {
                            Id = 16,
                            Name = "Фрезерные_6",
                            ParentMachineTypeId = 10
                        },
                        new
                        {
                            Id = 17,
                            Name = "Фрезерные_7",
                            ParentMachineTypeId = 10
                        },
                        new
                        {
                            Id = 18,
                            Name = "Фрезерные_8",
                            ParentMachineTypeId = 10
                        },
                        new
                        {
                            Id = 19,
                            Name = "Сверлильные"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Сверлильные_1",
                            ParentMachineTypeId = 19
                        },
                        new
                        {
                            Id = 21,
                            Name = "Сверлильные_2",
                            ParentMachineTypeId = 19
                        },
                        new
                        {
                            Id = 22,
                            Name = "Сверлильные_3",
                            ParentMachineTypeId = 19
                        },
                        new
                        {
                            Id = 23,
                            Name = "Сверлильные_4",
                            ParentMachineTypeId = 19
                        },
                        new
                        {
                            Id = 24,
                            Name = "ГРС"
                        },
                        new
                        {
                            Id = 25,
                            Name = "ГРС_1",
                            ParentMachineTypeId = 24
                        },
                        new
                        {
                            Id = 26,
                            Name = "ГРС_2",
                            ParentMachineTypeId = 24
                        },
                        new
                        {
                            Id = 27,
                            Name = "ГРС_3",
                            ParentMachineTypeId = 24
                        },
                        new
                        {
                            Id = 28,
                            Name = "Шлифовальные"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Шлифовальные_1",
                            ParentMachineTypeId = 28
                        },
                        new
                        {
                            Id = 30,
                            Name = "Шлифовальные_2",
                            ParentMachineTypeId = 28
                        },
                        new
                        {
                            Id = 31,
                            Name = "Шлифовальные_3",
                            ParentMachineTypeId = 28
                        },
                        new
                        {
                            Id = 32,
                            Name = "Шлифовальные_4",
                            ParentMachineTypeId = 28
                        },
                        new
                        {
                            Id = 33,
                            Name = "Шлифовальные_5",
                            ParentMachineTypeId = 28
                        },
                        new
                        {
                            Id = 34,
                            Name = "Долбежные"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Долбежные_1",
                            ParentMachineTypeId = 34
                        },
                        new
                        {
                            Id = 36,
                            Name = "Долбежные_2",
                            ParentMachineTypeId = 34
                        },
                        new
                        {
                            Id = 37,
                            Name = "Долбежные_3",
                            ParentMachineTypeId = 34
                        },
                        new
                        {
                            Id = 38,
                            Name = "Зубофрезерные"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Зубофрезерные_1",
                            ParentMachineTypeId = 38
                        },
                        new
                        {
                            Id = 40,
                            Name = "Зубофрезерные_2",
                            ParentMachineTypeId = 38
                        },
                        new
                        {
                            Id = 41,
                            Name = "Зубофрезерные_3",
                            ParentMachineTypeId = 38
                        },
                        new
                        {
                            Id = 42,
                            Name = "Зубофрезерные_4",
                            ParentMachineTypeId = 38
                        },
                        new
                        {
                            Id = 43,
                            Name = "Пресса"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Пресса_1",
                            ParentMachineTypeId = 43
                        },
                        new
                        {
                            Id = 45,
                            Name = "Пресса_2",
                            ParentMachineTypeId = 43
                        },
                        new
                        {
                            Id = 46,
                            Name = "Пресса_3",
                            ParentMachineTypeId = 43
                        },
                        new
                        {
                            Id = 47,
                            Name = "Пресса_4",
                            ParentMachineTypeId = 43
                        },
                        new
                        {
                            Id = 48,
                            Name = "Пресса_5",
                            ParentMachineTypeId = 43
                        },
                        new
                        {
                            Id = 49,
                            Name = "Пресса_6",
                            ParentMachineTypeId = 43
                        },
                        new
                        {
                            Id = 50,
                            Name = "Пресса_7",
                            ParentMachineTypeId = 43
                        },
                        new
                        {
                            Id = 51,
                            Name = "Пресса_8",
                            ParentMachineTypeId = 43
                        },
                        new
                        {
                            Id = 52,
                            Name = "Пресса_9",
                            ParentMachineTypeId = 43
                        },
                        new
                        {
                            Id = 53,
                            Name = "Пресса_10",
                            ParentMachineTypeId = 43
                        },
                        new
                        {
                            Id = 54,
                            Name = "Вальцы"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Вальцы_1",
                            ParentMachineTypeId = 54
                        },
                        new
                        {
                            Id = 56,
                            Name = "Вальцы_2",
                            ParentMachineTypeId = 54
                        },
                        new
                        {
                            Id = 57,
                            Name = "Листогибы"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Листогибы_1",
                            ParentMachineTypeId = 57
                        },
                        new
                        {
                            Id = 59,
                            Name = "Листогибы_2",
                            ParentMachineTypeId = 57
                        });
                });

            modelBuilder.Entity("UkrStanko.Models.App.Proposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<int>("PurshasePrice")
                        .HasColumnType("int");

                    b.Property<int>("SellingPrice")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("Proposals");
                });

            modelBuilder.Entity("UkrStanko.Models.App.ProposalImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Path")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("ProposalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProposalId");

                    b.ToTable("ProposalImages");
                });

            modelBuilder.Entity("UkrStanko.Models.App.ReadedNotices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ReadedNoticesCount")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReadedNotices");
                });

            modelBuilder.Entity("UkrStanko.Models.App.Requisition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("Requisitions");
                });

            modelBuilder.Entity("UkrStanko.Models.App.UserImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Path")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserImages");
                });

            modelBuilder.Entity("UkrStanko.Models.App.Machine", b =>
                {
                    b.HasOne("UkrStanko.Models.App.MachineType", "MachineType")
                        .WithMany()
                        .HasForeignKey("MachineTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MachineType");
                });

            modelBuilder.Entity("UkrStanko.Models.App.MachineType", b =>
                {
                    b.HasOne("UkrStanko.Models.App.MachineType", "ParentMachineType")
                        .WithMany()
                        .HasForeignKey("ParentMachineTypeId");

                    b.Navigation("ParentMachineType");
                });

            modelBuilder.Entity("UkrStanko.Models.App.Proposal", b =>
                {
                    b.HasOne("UkrStanko.Models.App.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("UkrStanko.Models.App.ProposalImage", b =>
                {
                    b.HasOne("UkrStanko.Models.App.Proposal", "Proposal")
                        .WithMany()
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("UkrStanko.Models.App.Requisition", b =>
                {
                    b.HasOne("UkrStanko.Models.App.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });
#pragma warning restore 612, 618
        }
    }
}
